### ISSUE TITLE
figure 1

### ISSUE THREAD

**Issue by pschloss** [SchlossLab/Sze_Obesity_mBio_2016#11]
@marcsze can you redo the pull request to upload the figure as `results/figures/flow_chart.png`? The image you uploaded was of pretty poor quality and didn't replace the exiting Figure 1.

**Comment by marcsze** [comment]
@pschloss Ok...I'll get that pull request right up again

**Comment by marcsze** [comment]
@pschloss I have just made a new pull request.  The last image added out of the three should have a quality that is good enough.  It is also larger than the original so by shrinking it you should also be able to increase the quality if it is still a problem.

**Comment by pschloss** [comment]
ack, did you mean to include a box to indicate what happened between n=11 and n=10?

**Comment by marcsze** [comment]
@pschloss  what do you mean?

**Comment by pschloss** [comment]
it goes from N=11 to N=10 without a box pulled out to the right indicating what happened to the N=1

**Comment by marcsze** [comment]
Do you want me to add a box to it?  We explain in the online supplement that one study did not have any Obese individuals so it was excluded.

**Comment by pschloss** [comment]
Sure - add the box.

**Comment by marcsze** [comment]
I made a new pull request with the extra box.  It should be a good enough quality but let me know if it isn't.
