### ISSUE TITLE
One last look

### ISSUE THREAD

**Issue by pschloss** [SchlossLab/Sze_Obesity_mBio_2016#20]
@marcsze could you take a look at the PDF in submission and make sure everything looks good? Once I get word back from you, I'll update the line numbers in the Response to Reviewers document

**Comment by marcsze** [comment]
@pschloss overall it looks pretty good to me.  Just a few changes or potential areas for clarification that I noticed.  Let me know if you need anything else and when you plan to re-submit.

line 84 extra from

line 167 0.13 and 0.082 as a percent seem small do we mean 13 and 8.2 percent or was it really this small?

line 192 and line 196 one mentions Shannon index and the other mentions Shannon diversity.  Should one be observed richness?  Not sure what the difference is between these two.

line 233 "amount variation" to "amount of variation"

line 322 should we mention that it was an average of 100 iterations?
