### ISSUE TITLE
Cross validation with cross_validate.R

### ISSUE THREAD

**Issue by carden24** [SchlossLab/Sze_Obesity_mBio_2016#22]
First of all, thanks for having all the scripts here. It helps to understand your approach, and shows your commitment to open science.
I have a question on one of your steps. More specifically, I noticed in your scripts that you used a custom function for cross-validation instead of the one provided in the aucRF package. Could you elaborate on the reason? (You say there is a bug ).  I am using it and I am surprised that the average cvAUC I get is way lower than I expected when I compared it to the one obtained from running my model with all the datapoints.

**Comment by marcsze** [comment]
Thanks for the question.  For clarification is the data that you are talking about your own data or data that was used in this manuscript?  Also did you run the 10 cvAUC's that are default in the script? If so what was the value you obtained on the full data set and the range of cv AUCs?

**Comment by carden24** [comment]
I am testing your scripts but I am using my own dataset, so I think that I have problems with overfitting (comparing my AUC from the whole set vs. the cross validated AUC).  

I have not used your data for evaluation. I am just curious why you changed the cross-validation function. I have compared both and while I understand them in broad terms I do not know where the bug is. 
thanks again for your time, I understand that this was published a while ago.

**Comment by pschloss** [comment]
If I recall correctly, when we ran the built in cross-validation we were getting screwy results because some cross validation iterations would return AUCs less than 0.5 because it was switching what it considered a case and control. Wishing I had written a better commit message right now...

**Comment by carden24** [comment]
Great, make sense. I compared the two formulas and I received an average AUC of 0.23 with the formula from the R package and 0.818 with the one from the paper. Thanks a lot for the quick response.
